### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Tempuser8734** [raeleus/AHK-Macro-Recorder#1]
Running the script as an administrator. Win 10,

1 - right after start pressing F1 -  "Script File Not Found - C:\Users\*\AppData\Local\Temp\~Record1.ahk"
2 - creating C:\Users\*\AppData\Local\Temp\~Record1.ahk manually, no crash, but nothing gets written after start and stop recording
3 - long pressing F1 - "SHOW SOURCE" on the screen -> ahk error handler:

Error: Failed attempt to launch program or document:
Action: <C:\Users\Irek\AppData\Local\Programs\Microsoft VS Code\Code.exe>
Params: <"C:\Users\Irek\AppData\Local\Temp\~Record1.ahk">

Specifically: <Specified file cannot be found.>translated from polish

	205: {
	207: }
▶	208: Run(""" EnvGet("LocalAppData") "\Programs\Microsoft VS Code\Code.exe" "" LogFile """)
	209: Return
	210: }

**Comment by Tempuser8734** [comment]
Ahk 2.0.18

**Comment by Tempuser8734** [comment]
I have tested the inspiration V1 script and managed to get it working after compiling to exe with 1.x option and placing the program in ahk dir inside program files.
Any special requirements for V2 version?

**Comment by raeleus** [comment]
For #1, you have to record a macro first. Long press f1 until you see the text "record", then do the actions you want replicated in the macro.

For #3, you have to make sure vs code is installed. If you do have it installed, make sure the path matches what I have in the script. If not, feel free to modify the line in the source.

For #2, you shouldn't have made the file manually. Maybe ahk doesn't have permission to overwrite the file now. Try deleting the file, then record the macro like I said above.

**Comment by Tempuser8734** [comment]
I have just noticed the test on the screen when pressing F1 ;-)
1-correct
2-no longer a problem
3-replaced it with notepad++ location and it works for me
Thanks for help

**Comment by raeleus** [comment]
Thank you so much!
